version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: movie-recommendation-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie_recommendation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-recommendation-app
    ports:
      - "3000:3000"  # Frontend
      - "3001:3001"  # Backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/movie_recommendation?schema=public
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy

  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-recommendation-prisma-studio
    command: npx prisma studio
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/movie_recommendation?schema=public
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: 